Switch to WS-based JSON file output from old game output.
rollerderby/scoreboard pull request #146
Opened 2018-08-25 17:27 UTC by brian-brazil

I had to take care of #12 while doing this, and also found another regression from #130.

I'll leave using this new setup for unittests to another PR.

@AdamSmasherDerby This switches to the new JSON format if you want to poke around

2018-08-26 15:03 UTC, brian-brazil commented
I've also added the tests for ScoreBoardJSONListener, and had to incorporate #144 as the new unittests caught that bug.

2018-08-31 15:32 UTC, AdamSmasherDerby commented
I like this!  Using the clock time plus the team names in the file name is a good idea - humans can see what they're looking at.

2018-09-10 20:10 UTC, frank-weinberg requested changes
Looks good in general. Just some formatting, a bunch of unused includes, the name for custom settings and the exposing of internal details of DefaultClockModel. (The fix for the latter might be better suited for a separate PR.)

2018-09-10 20:10 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/jetty/WS.java
>  import java.util.LinkedList;
LinkedList is unused

2018-09-10 20:10 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/json/JSONStateManager.java
> +  public synchronized void register(JSONStateListener source) {
This file is indented with 2 spaces instead of 1 tab. (Consistent within the file but inconsistent with the existing code.)

2018-09-10 20:10 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/json/ScoreBoardJSONListener.java
> -	private WS ws;
This makes WS an unused import.

2018-09-10 20:10 UTC, frank-weinberg commented on tests/com/carolinarollergirls/scoreboard/json/JSONStateManagerTest.java
> +import static org.junit.Assert.assertTrue;
Everything from Assert except assertEquals is unused.

2018-09-10 20:10 UTC, frank-weinberg commented on tests/com/carolinarollergirls/scoreboard/json/JSONStateManagerTest.java
> +import java.util.HashSet;
HashSet is unused.

2018-09-10 20:10 UTC, frank-weinberg commented on tests/com/carolinarollergirls/scoreboard/json/JSONStateManagerTest.java
> +  private JSONStateManager jsm;
This file is also indented with spaces.

2018-09-10 20:10 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/CustomSettings.java
> +	public static final String EVENT_SETTING = "Custom";
We should not use "Custom" for settings that belong to the core distribution. I suggest "Frontend" instead.

Also we should use this String constant instead of retyping the string each time it is used. (This also applies to the other elements of the WS and XML. We should aim to migrate the code over time.)

2018-09-10 20:10 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/defaults/DefaultCustomSettingsModel.java
> +import java.util.List;
List is unused.

2018-09-10 20:10 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/CustomSettings.java
> +public interface CustomSettings extends ScoreBoardEventProvider {
Do we really need a separate set of interfaces and class for this? It seems like a second instance of DefaultSettingsModel would also work and avoid the duplicated code.

2018-09-10 20:10 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/xml/ScoreBoardXmlListener.java
> +			CustomSettingsModel settings = (CustomSettingsModel)p;
settings is unused.

2018-09-10 20:10 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/ScoreBoardManager.java
>  import java.util.Iterator;
ArrayList, List and Iterator are unused.

2018-09-10 20:10 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/model/CustomSettingsModel.java
> +import java.util.Map;
Map is unused.

2018-09-10 20:10 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/json/JSONStateSnapshotter.java
> +import java.util.Date;
Date is unused.

2018-09-10 20:10 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/json/JSONStateSnapshotter.java
> +import com.fasterxml.jackson.core.TreeNode;
TreeNode is unused.

2018-09-10 20:10 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/json/JSONStateSnapshotter.java
> +  public JSONStateSnapshotter(JSONStateManager jsm, File directory) {
File is indented with spaces.

2018-09-10 20:10 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/defaults/DefaultPositionModel.java
> -				ScoreBoardManager.gameSnapshot();
This makes ScoreBoardManager an unused import.

2018-09-10 20:10 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/defaults/DefaultScoreBoardModel.java
> -				ScoreBoardManager.gameSnapshot();
This makes ScoreBoardManager an unused import.

2018-09-10 20:10 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/defaults/DefaultSkaterModel.java
> -			ScoreBoardManager.gameSnapshot();
This makes ScoreBoardManager an unused import.

2018-09-10 20:10 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/defaults/DefaultTeamModel.java
> -		ScoreBoardManager.gameSnapshot();
This makes ScoreBoardManager an unused import.

2018-09-10 20:10 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/defaults/DefaultClockModel.java
> +	public static UpdateClockTimerTask updateClockTimerTask = new UpdateClockTimerTask();
We should not expose these implementation details. If we need to ba able to meddle with the RTC, we should add a RTC utility class, that the update task then uses.

2018-09-10 20:10 UTC, frank-weinberg commented on tests/com/carolinarollergirls/scoreboard/json/ScoreBoardJSONListenerTests.java
> +import com.carolinarollergirls.scoreboard.ScoreBoard;
ScoreBoard is unused.

2018-09-10 20:10 UTC, frank-weinberg commented on tests/com/carolinarollergirls/scoreboard/json/ScoreBoardJSONListenerTests.java
> +import com.carolinarollergirls.scoreboard.jetty.JettyServletScoreBoardController;
event.* are all unused.

2018-09-10 20:10 UTC, frank-weinberg commented on tests/com/carolinarollergirls/scoreboard/json/ScoreBoardJSONListenerTests.java
> +import com.carolinarollergirls.scoreboard.model.ClockModel;
ClockModel is unused.

2018-09-10 20:10 UTC, frank-weinberg commented on tests/com/carolinarollergirls/scoreboard/json/ScoreBoardJSONListenerTests.java
> +  private DefaultScoreBoardModel sbm;
File is indented with spaces.

2018-09-11 13:40 UTC, brian-brazil commented on src/com/carolinarollergirls/scoreboard/json/JSONStateManager.java
> +  public synchronized void register(JSONStateListener source) {
As previously discussed, I'm going to do a big reformat once we've no big changes pending.

2018-09-11 13:41 UTC, brian-brazil commented on src/com/carolinarollergirls/scoreboard/defaults/DefaultClockModel.java
> +	public static UpdateClockTimerTask updateClockTimerTask = new UpdateClockTimerTask();
As discussed in person, it sounds like you'll be reworking all this in future.

2018-09-11 13:43 UTC, brian-brazil commented on src/com/carolinarollergirls/scoreboard/CustomSettings.java
> +public interface CustomSettings extends ScoreBoardEventProvider {
Yes, it'd not work on the XML side due to the duplicated providerName. It also makes it a bit clearer that none of the rule stuff applies here, and that these are only strings.

2018-09-11 14:20 UTC, brian-brazil commented on src/com/carolinarollergirls/scoreboard/CustomSettings.java
> +	public static final String EVENT_SETTING = "Custom";
Done

2018-09-11 15:10 UTC, brian-brazil commented
That's all updated and pushed, PTAL.

2018-09-11 18:29 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/CustomSettings.java
> +public interface CustomSettings extends ScoreBoardEventProvider {
Having multiple instances of DefaultClockModel works. A quick look at the class indicates that it has a providerId set in addition to the provider Name. I didn't check if this is actually sufficient, but if it is, I'd say this is better than duplicating code.

2018-09-11 18:35 UTC, frank-weinberg commented on src/com/carolinarollergirls/scoreboard/json/JSONStateManager.java
> +  public synchronized void register(JSONStateListener source) {
I'd still prefer we don't knowingly introduce inconsistencies. Who knows, when this reformat will actually take place.

2018-09-11 18:37 UTC, frank-weinberg commented
There's 2 more unused imports, that I missed commenting on the first review:
- com.carolinarollergirls.scoreboard.Skater in TeamModel.java
- com.carolinarollergirls.scoreboard.ScoreBoardManager in JSONServlet.java

2018-09-11 21:38 UTC, brian-brazil commented on src/com/carolinarollergirls/scoreboard/CustomSettings.java
> +public interface CustomSettings extends ScoreBoardEventProvider {
That'd get messy on the XML side, the event system isn't good enough to handle that number of parameters. FrontendSettings is also quite a lot simpler than the main Settings, and I'd hope long term to get rid of Settings.

2018-09-11 21:42 UTC, brian-brazil commented on src/com/carolinarollergirls/scoreboard/json/JSONStateManager.java
> +  public synchronized void register(JSONStateListener source) {
I'm mainly waiting on your changes to go in.

2018-09-11 21:42 UTC, brian-brazil commented
I've removed those unused imports.

2018-09-11 22:17 UTC, frank-weinberg approved these changes

2018-09-11 22:18 UTC, merged